# Generated by Django 5.0.1 on 2024-02-05 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PLANT', models.CharField(blank=True, max_length=255, null=True)),
                ('PROJECT', models.CharField(blank=True, max_length=255, null=True)),
                ('REGION', models.CharField(blank=True, max_length=255, null=True)),
                ('DATE', models.DateField(blank=True, null=True)),
                ('TIME', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
