# Generated by Django 5.0.1 on 2024-02-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0004_sentdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentdetails',
            old_name='DATE',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sentdetails',
            old_name='PLANT',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='sentdetails',
            old_name='PROJECT',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='sentdetails',
            old_name='REGION',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='sentdetails',
            old_name='TIME',
            new_name='time',
        ),
    ]
