# Generated by Django 5.0.1 on 2024-02-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0009_alter_projectinfo_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
