# Generated by Django 5.0.1 on 2024-01-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'employee'), ('admin', 'admin')], default='employee', max_length=255),
        ),
    ]
