# Generated by Django 5.0.1 on 2024-02-06 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0005_rename_date_sentdetails_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filepath', models.TextField(blank=True, max_length=255, null=True)),
                ('plant', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_body', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
