# Generated by Django 5.0.1 on 2024-02-06 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0006_scheduledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('project_wps', models.CharField(blank=True, max_length=255, null=True)),
                ('plantid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UDS_App.plantinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Plant_Project_Info',
        ),
    ]
