# Generated by Django 5.0.1 on 2024-02-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0007_plantinfo_projectinfo_delete_plant_project_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='plantid',
            new_name='plant',
        ),
    ]
