# Generated by Django 5.0.1 on 2024-02-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDS_App', '0008_rename_plantid_projectinfo_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='plant',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='UDS_App.plantinfo'),
        ),
    ]
